# Generated by Django 6.0.5 on 2026-08-21 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('birthdaygreetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('role', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff/Teacher')], default='student', max_length=10)),
                ('grade_or_department', models.CharField(blank=True, help_text='e.g., Grade 10 or Science Dept', max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='birthdays/')),
                ('custom_message', models.CharField(blank=True, help_text='Optional special greeting message from administration.', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
