# Generated by Django 6.0.5 on 2026-09-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_alumni_group_to_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('access_teacher_dashboard', 'Can access teacher dashboard'), ('access_student_dashboard', 'Can access student dashboard'), ('access_parent_dashboard', 'Can access parent dashboard'), ('manage_school_operations', 'Can manage school operations (invoices, results, timetable admin)')]},
        ),
        migrations.AddField(
            model_name='profile',
            name='access_code',
            field=models.CharField(blank=True, help_text='Unique login code generated at registration, issued out by the admin.', max_length=20, unique=True),
        ),
    ]
