<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_convert_duration_seconds_to_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in minutes. Null for no limit.', null=True),
        ),
    ]
=======
# Generated by Django 5.2.7 on 2025-10-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_convert_duration_seconds_to_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in minutes. Null for no limit.', null=True),
        ),
    ]
>>>>>>> a79162f0f57a88911ff8216bfa0a9b5b9f1aa1a5
