# Generated by Django 5.2.7 on 2025-10-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_convert_duration_seconds_to_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in minutes. Null for no limit.', null=True),
        ),
    ]
