# Generated by Django 6.0.5 on 2026-08-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_studentresultsheet_studentattendancerecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresultsheet',
            name='principal_signature',
            field=models.ImageField(blank=True, null=True, upload_to='principal_signatures/'),
        ),
        migrations.AddField(
            model_name='studentresultsheet',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='result_photos/'),
        ),
        migrations.AddField(
            model_name='studentresultsheet',
            name='teacher_signature',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_signatures/'),
        ),
    ]
