# Generated by Django 6.0.5 on 2026-08-21 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('target_audience', models.CharField(choices=[('ALL', 'All'), ('STUDENTS', 'Students Only'), ('TEACHERS', 'Teachers Only'), ('PARENTS', 'Parents Only')], default='ALL', max_length=10)),
                ('is_important', models.BooleanField(default=False, help_text='Pin this announcement to top')),
                ('is_published', models.BooleanField(default=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_important', '-created_at'],
            },
        ),
    ]
